name: stockjet
description: A new Flutter project.
version: 1.0.0+1

environment:
    sdk: '>=2.5.2 <3.0.0'

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^0.1.2

    charts_flutter: ^0.8.1

    simple_design: ^1.0.3

    material_design_icons_flutter: ^3.4.4995

    flutter_custom_tabs: ^0.6.0

    share: ^0.6.3+6

    shared_preferences: ^0.5.6+2

    cached_network_image: ^2.0.0

dev_dependencies:
    flutter_launcher_icons: ^0.7.4

flutter:
    uses-material-design: true

    fonts:
        - family: Kollektif
          fonts:
              - asset: fonts/Kollektif-Bold.ttf
              - asset: fonts/Kollektif.ttf
                weight: 700
